NomeDoCliente = input("Digite o nome do cliente")
DiaDeVencimento = input("Digite o dia de vencimento")
MesDeVencimento = input("Digite o mês de vencimento")
ValorDaFatura = input("Digite o valor da fatura")
print("Olá,",NomeDoCliente)
print("A sua fatura com vencimento em",DiaDeVencimento,"de",MesDeVencimento,"no valor de R$",ValorDaFatura,"está fechada.")